.catalog:
    name: "storage-bridge for ceph"
    version: "v1.0.0"
    description: "storage-bridge for ceph"
    questions:
     - variable: "CEPH_MONITOR"
       label: "Ceph Monitor(192.168.15.13:6789)"
       required: true
       type: "string"
     - variable: "CEPH_DEFAULT_VOLUME_POOL"
       label: "Ceph Storage Pool(rep-pool)"
       type: "string"
       required: true
     - variable: "CEPH_DEFAULT_VOLUME_SIZE"
       label: "Ceph Default Volume Size"
       type: "string"
     - variable: "CEPH_DEFAULT_FORMAT_FILESYSTEM"
       label: "Ceph Format File System Type(xfs)"
       type: "string"

storage-bridge:
    metadata:
        ceph_monitor: "${CEPH_MONITOR}"
        ceph_default_volume_pool: "${CEPH_DEFAULT_VOLUME_POOL}"
        ceph_default_volume_size: "${CEPH_DEFAULT_VOLUME_SIZE}"
        ceph_default_format_filesystem: "${CEPH_DEFAULT_FORMAT_FILESYSTEM}"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

storage-bridge-storagepool:
    metadata:
        ceph_monitor: "${CEPH_MONITOR}"
        ceph_default_volume_pool: "${CEPH_DEFAULT_VOLUME_POOL}"
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
